version: '3.9'

services:
  telegram-bot:
    build:
      context: ./            # Context is the root directory (since Dockerfile is inside 'app' folder)
      dockerfile: ./app/Dockerfile  # Dockerfile is inside the 'app' folder
    volumes:
      - ./app:/app       # Mount the local 'app' directory to '/app' inside the container
      - telegram_data:/app/data
    ports:
      - "8443:8443"      # Optional, only if you need to expose a port
    restart: always
volumes:
  telegram_data:

  message-forwarder:
    build:
      context: .
    volumes:
      - ./data:/app/data  # Persist data (optional, for session files)
    restart: always
    depends on: 
      - telegram-bot
    command: python forwarder.py  # Run the message forwarder service
