version: '3.8'

services:
  telegram-bot:
    build:
      context: ./app     
      dockerfile: Dockerfile  
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - PHONE_NUMBER=${PHONE_NUMBER}
    volumes:
      - ./app:/app       # Mount the app directory to the container
    ports:
      - "8443:8443"      # Optional: expose ports if necessary for webhook
    restart: always
